export const books = [
	{
		id: '1',
		title: 'Northanger Abbey',
		year: 1814,
		edition: 'Penguin',
		price: 18.2,
	},
	{
		id: '2',
		title: 'War and Peace',
		year: 1865,
		edition: 'Penguin',
		price: 12.7,
	},
	{
		id: '3',
		title: 'Anna Karenina',
		year: 1875,
		edition: 'Penguin',
		price: 13.5,
	},
	{
		id: '4',
		title: 'Mrs. Dalloway',
		year: 1925,
		edition: 'Harcourt Brace',
		price: 25,
	},
	{
		id: '5',
		title: 'The Hours',
		year: 1999,
		edition: 'Harcourt Brace',
		price: 12.35,
	},
	{
		id: '6',
		title: 'Huckleberry Finn',
		year: 1865,
		edition: 'Penguin',
		price: 5.76,
	},
	{
		id: '7',
		title: 'Bleak House',
		year: 1870,
		edition: 'Random House',
		price: 5.75,
	},
	{
		id: '8',
		title: 'Tom Sawyer',
		year: 1862,
		edition: 'Random House',
		price: 7.75,
	},
	{
		id: '9',
		title: "A Room of One's Own",
		year: 1922,
		edition: 'Penguin',
		price: 29,
	},
	{
		id: '10',
		title: 'Harry Potter',
		year: 2000,
		edition: 'Harcourt Brace',
		price: 19.95,
	},
	{
		id: '11',
		title: 'One Hundred Years of Solitude',
		year: 1967,
		edition: 'Harper  Perennial',
		price: 14,
	},
	{
		id: '12',
		title: 'Hamlet, Prince of Denmark',
		year: 1603,
		edition: 'Signet  Classics',
		price: 7.95,
	},
	{
		id: '13',
		title: 'Lord of the Rings',
		year: 1937,
		edition: 'Penguin',
		price: 27.45,
	},
];
